from .coco import COCO
from .voc import VOC
from .ade20k import ADE20K
from .cityscapes import CityScapes
from .adaspace import Adaspace
from .huawei import Huawei
from .thunder import Thunder
from .road import Road
from .road_2 import Road2
from .potsdam import Potsdam
from .hrnet import HRNet
from .loveda import Loveda
